#!/bin/sh
# Generated by setup-experiment.sh — do not edit. Regenerate by
# re-running setup-experiment.
case "$1" in
  get)
    cat <<'EOF_INNER'
username=eden
password=8fc3e15002f2ae611d10f7fde589aad568f99372b12a57031fd429480ac9eece
EOF_INNER
    ;;
esac
