#!/bin/sh
# Generated by setup-experiment.sh — do not edit. Regenerate by
# re-running setup-experiment.
case "$1" in
  get)
    cat <<'EOF_INNER'
username=eden
password=cc70dd42dcba184dccbd8aa4ec0033640aefe72fa44453a19a4c87e038308f7e
EOF_INNER
    ;;
esac
