#!/bin/sh
# Generated by setup-experiment.sh — do not edit. Regenerate by
# re-running setup-experiment.
case "$1" in
  get)
    cat <<'EOF_INNER'
username=eden
password=0bc9743b79d7706e2b124377b158c3902d601813d47386dc5f9a6daf4112e68b
EOF_INNER
    ;;
esac
