#!/bin/sh
# Generated by setup-experiment.sh — do not edit. Regenerate by
# re-running setup-experiment.
case "$1" in
  get)
    cat <<'EOF_INNER'
username=eden
password=35a632f28a7bc6f4d58c0fc1686529ec0e6a0a0de09a26f8e0079c0276590632
EOF_INNER
    ;;
esac
