{{- if and (eq (include "eden.appEnabled" .) "true") .Values.ingress.enabled }}
{{- $fullName := include "eden.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-web-ui
  labels:
    {{- include "eden.componentLabels" (dict "ctx" . "component" "web-ui") | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ include "eden.webUiHost" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-web-ui
                port:
                  number: 8090
{{- end }}
