#!/bin/sh
# Generated by setup-experiment.sh — do not edit. Regenerate by
# re-running setup-experiment.
case "$1" in
  get)
    cat <<'EOF_INNER'
username=eden
password=904ca94227c644594b42c5530bb0c0dd50520774205d7e384e8dddc28ca0e850
EOF_INNER
    ;;
esac
